package no.kommune.homecare.nurse;

public enum Qualification {
    REGISTERED_NURSE,
    AUXILIARY_NURSE,
    HEALTHCARE_ASSISTANT,
    WOUND_CARE_SPECIALIST,
    PALLIATIVE_CARE_SPECIALIST,
    DEMENTIA_CARE_SPECIALIST,
    MEDICATION_ADMINISTRATION
}
